/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsSupportRouteImport } from './routes/docs.support'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsFeaturesRouteImport } from './routes/docs.features'
import { Route as DocsFaqRouteImport } from './routes/docs.faq'
import { Route as DocsDeveloperRouteImport } from './routes/docs.developer'
import { Route as DocsDashboardRouteImport } from './routes/docs.dashboard'
import { Route as DocsChangelogRouteImport } from './routes/docs.changelog'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsCommandsIndexRouteImport } from './routes/docs.commands.index'
import { Route as DocsGuidesPermissionsRouteImport } from './routes/docs.guides.permissions'
import { Route as DocsGuidesConfigurationRouteImport } from './routes/docs.guides.configuration'
import { Route as DocsGuidesSlugRouteImport } from './routes/docs.guides.$slug'
import { Route as DocsCommandsCategoryRouteImport } from './routes/docs.commands.$category'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSupportRoute = DocsSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFeaturesRoute = DocsFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDeveloperRoute = DocsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDashboardRoute = DocsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DocsRoute,
} as any)
const DocsChangelogRoute = DocsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCommandsIndexRoute = DocsCommandsIndexRouteImport.update({
  id: '/commands/',
  path: '/commands/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesPermissionsRoute = DocsGuidesPermissionsRouteImport.update({
  id: '/guides/permissions',
  path: '/guides/permissions',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesConfigurationRoute = DocsGuidesConfigurationRouteImport.update({
  id: '/guides/configuration',
  path: '/guides/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesSlugRoute = DocsGuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCommandsCategoryRoute = DocsCommandsCategoryRouteImport.update({
  id: '/commands/$category',
  path: '/commands/$category',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/developer': typeof DocsDeveloperRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/support': typeof DocsSupportRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/commands/$category': typeof DocsCommandsCategoryRoute
  '/docs/guides/$slug': typeof DocsGuidesSlugRoute
  '/docs/guides/configuration': typeof DocsGuidesConfigurationRoute
  '/docs/guides/permissions': typeof DocsGuidesPermissionsRoute
  '/docs/commands/': typeof DocsCommandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/developer': typeof DocsDeveloperRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/support': typeof DocsSupportRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs': typeof DocsIndexRoute
  '/docs/commands/$category': typeof DocsCommandsCategoryRoute
  '/docs/guides/$slug': typeof DocsGuidesSlugRoute
  '/docs/guides/configuration': typeof DocsGuidesConfigurationRoute
  '/docs/guides/permissions': typeof DocsGuidesPermissionsRoute
  '/docs/commands': typeof DocsCommandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/developer': typeof DocsDeveloperRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/features': typeof DocsFeaturesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/support': typeof DocsSupportRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/commands/$category': typeof DocsCommandsCategoryRoute
  '/docs/guides/$slug': typeof DocsGuidesSlugRoute
  '/docs/guides/configuration': typeof DocsGuidesConfigurationRoute
  '/docs/guides/permissions': typeof DocsGuidesPermissionsRoute
  '/docs/commands/': typeof DocsCommandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/api'
    | '/docs/changelog'
    | '/docs/dashboard'
    | '/docs/developer'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/installation'
    | '/docs/support'
    | '/docs/troubleshooting'
    | '/docs/'
    | '/docs/commands/$category'
    | '/docs/guides/$slug'
    | '/docs/guides/configuration'
    | '/docs/guides/permissions'
    | '/docs/commands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/docs/api'
    | '/docs/changelog'
    | '/docs/dashboard'
    | '/docs/developer'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/installation'
    | '/docs/support'
    | '/docs/troubleshooting'
    | '/docs'
    | '/docs/commands/$category'
    | '/docs/guides/$slug'
    | '/docs/guides/configuration'
    | '/docs/guides/permissions'
    | '/docs/commands'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/sitemap.xml'
    | '/docs/api'
    | '/docs/changelog'
    | '/docs/dashboard'
    | '/docs/developer'
    | '/docs/faq'
    | '/docs/features'
    | '/docs/installation'
    | '/docs/support'
    | '/docs/troubleshooting'
    | '/docs/'
    | '/docs/commands/$category'
    | '/docs/guides/$slug'
    | '/docs/guides/configuration'
    | '/docs/guides/permissions'
    | '/docs/commands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/support': {
      id: '/docs/support'
      path: '/support'
      fullPath: '/docs/support'
      preLoaderRoute: typeof DocsSupportRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/features': {
      id: '/docs/features'
      path: '/features'
      fullPath: '/docs/features'
      preLoaderRoute: typeof DocsFeaturesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/developer': {
      id: '/docs/developer'
      path: '/developer'
      fullPath: '/docs/developer'
      preLoaderRoute: typeof DocsDeveloperRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dashboard': {
      id: '/docs/dashboard'
      path: '/dashboard'
      fullPath: '/docs/dashboard'
      preLoaderRoute: typeof DocsDashboardRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/changelog': {
      id: '/docs/changelog'
      path: '/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof DocsChangelogRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/commands/': {
      id: '/docs/commands/'
      path: '/commands'
      fullPath: '/docs/commands/'
      preLoaderRoute: typeof DocsCommandsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides/permissions': {
      id: '/docs/guides/permissions'
      path: '/guides/permissions'
      fullPath: '/docs/guides/permissions'
      preLoaderRoute: typeof DocsGuidesPermissionsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides/configuration': {
      id: '/docs/guides/configuration'
      path: '/guides/configuration'
      fullPath: '/docs/guides/configuration'
      preLoaderRoute: typeof DocsGuidesConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides/$slug': {
      id: '/docs/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/docs/guides/$slug'
      preLoaderRoute: typeof DocsGuidesSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/commands/$category': {
      id: '/docs/commands/$category'
      path: '/commands/$category'
      fullPath: '/docs/commands/$category'
      preLoaderRoute: typeof DocsCommandsCategoryRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsChangelogRoute: typeof DocsChangelogRoute
  DocsDashboardRoute: typeof DocsDashboardRoute
  DocsDeveloperRoute: typeof DocsDeveloperRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsFeaturesRoute: typeof DocsFeaturesRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsSupportRoute: typeof DocsSupportRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsCommandsCategoryRoute: typeof DocsCommandsCategoryRoute
  DocsGuidesSlugRoute: typeof DocsGuidesSlugRoute
  DocsGuidesConfigurationRoute: typeof DocsGuidesConfigurationRoute
  DocsGuidesPermissionsRoute: typeof DocsGuidesPermissionsRoute
  DocsCommandsIndexRoute: typeof DocsCommandsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsChangelogRoute: DocsChangelogRoute,
  DocsDashboardRoute: DocsDashboardRoute,
  DocsDeveloperRoute: DocsDeveloperRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsFeaturesRoute: DocsFeaturesRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsSupportRoute: DocsSupportRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsCommandsCategoryRoute: DocsCommandsCategoryRoute,
  DocsGuidesSlugRoute: DocsGuidesSlugRoute,
  DocsGuidesConfigurationRoute: DocsGuidesConfigurationRoute,
  DocsGuidesPermissionsRoute: DocsGuidesPermissionsRoute,
  DocsCommandsIndexRoute: DocsCommandsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
